### ISSUE TITLE
Include a license file

### ISSUE THREAD

**Issue by Cactus-man** [PolyMeilex/cargo-wgsl#14]
I assume contributions are welcome, because this is uploaded to github and available publicly, but as far as I know this falls under rights reserved. I have no background with copyright and only know what I found online, e.g. [here](https://choosealicense.com/no-permission/).

**Comment by Cactus-man** [comment]
This seems to be related to [vscode-wgsl](https://github.com/PolyMeilex/vscode-wgsl), which includes the MIT license, so it really looks like an oversight.

**Comment by PolyMeilex** [comment]
MIT was defined on crates.io: https://github.com/PolyMeilex/cargo-wgsl/blob/955c21b1ea20cc0a8746632d062cfe11d8f7a325/Cargo.toml#L9 but yeah there should be a full license copy.
Commited here https://github.com/PolyMeilex/cargo-wgsl/blob/master/LICENSE

**Comment by Cactus-man** [comment]
Thanks a lot
