### ISSUE TITLE
Return non-zero exit code on err

### ISSUE THREAD

**Issue by MinusGix** [PolyMeilex/cargo-wgsl#5]
Returning a non-zero exit code when errors are discovered would allow chaining like: `cargo-wsgl && cargo run` where it only runs the program if the shaders are good. This would help when purely working in the terminal or on an editor other than vscode.

**Comment by PolyMeilex** [comment]
Oh, that's great, I definitely want to support this workflow. Thank you for suggestion, I will look into that, it should be easy to add

**Comment by PolyMeilex** [comment]
Done in `0.0.6` release, thank you!
